### ISSUE TITLE
Share BraTs2023 Datasets

### ISSUE THREAD

**Issue by tanjia123456** [faizan1234567/Brain-Tumors-Segmentation#9]
Hi, thanks for your contribution! I would like to do brain glioma segmentation, could you please share the dataset? The team on the official website has closed, and I cannot download the dataset.

**Comment by faizan1234567** [comment]
@tanjia123456 you can download the dataset from kaggle: https://www.kaggle.com/datasets/shakilrana/brats-2023-adult-glioma

**Comment by aylive** [comment]
> @tanjia123456 you can download the dataset from kaggle: https://www.kaggle.com/datasets/shakilrana/brats-2023-adult-glioma

Thanks for sharing! But I met a problem when accessing the dataset.

I downloaded the dataset. But after unzipping, there's only 262 samples for training and 36 samples for test. This is far less than the official number (training 1251, test 219). I found this is because many sample directories listed on this kaggle datacard have only empty subfolders, which will then be lost after unzipping. 

I'm confused, have you met the problem?
